### ISSUE TITLE
Requirements Draft - Tech Stack and alternative options

### ISSUE THREAD

**Issue by NeilanshTriesToCode** [COSC-499-EquiFood-B/EquiFoodApp-B#13]
Identify the tech stack you plan to use. If this is the tech stack required by your client, then state that in the document. If your client is flexible, you must indicate a clear rationale of the choice made. This means an extra page with a table of at least 3 options and document all pros and cons for each before letting your client make a choice.

**Comment by NeilanshTriesToCode** [comment]
**React Native:**
- Built on JS/TS
- May be slower (performance wise).
- Development may be slower than Flutter*.
- Readable Components, so easy to debug code.
- Requires installing 3rd party NPM packages/APIs for animations, UI Components/Widgets.
- Known to have issues with continuous location tracking, using camera.
- Load time may be slower.

**Flutter:**
- Built on Dart (similar to Java syntax).
- Faster than Native (performance wise).
- Development may be faster than React Native*.
- Component Trees may not be readable. Debugging may take some effort.
- Provides built-in plugins by Google like Maps (which will come handy). 
- Provides several built-in UI Widgets/Components.
- Also provides other actions such as accessing phone camera (which may require installing packages in case of Native), etc.
- Works well with location tracking as Google plugins are provided.
- Loads pretty quickly.

_***I read in a few places that Flutter is a better choice in case we're on a time crunch and have to deliver our MVP at the earliest.**_

**Similarities:**
- Both support iOS and android devices.
- Both have Hot Loading.

**Comment by NeilanshTriesToCode** [comment]
Link for comparison: https://nix-united.com/blog/flutter-vs-react-native/
Another link: https://www.nomtek.com/blog/flutter-vs-react-native

**Comment by anamicasunder** [comment]
Team has chosen to proceed with Flutter after last meeting with client
