### ISSUE TITLE
Create Class in backend folder for Donations-related functions

### ISSUE THREAD

**Issue by NeilanshTriesToCode** [COSC-499-EquiFood-B/EquiFoodApp-B#140]
_Auth-related code such as logging in, creating/editing user goes into the ``auth`` folder. 
Backend-related code like read/write operations and querying the database goes into the ``backend`` folder._

- For this Issue specifically, create a ``Class`` file in the ``backend`` to query the ``donations`` Collection from firebase.
- Could contain read/write methods such as getting details, getting details by a certain order, creating new donations etc.

**Comment by minhhbt** [comment]
Done
