### ISSUE TITLE
Remove loading 

### ISSUE THREAD

**Issue by minhhbt** [COSC-499-EquiFood-B/EquiFoodApp-B#210]
Remove loading text on indiv and restaurant dashboard.

**Comment by NeilanshTriesToCode** [comment]
- Added a Loading Indicator ``CircularProgressionIndicator`` while the data is being read.
- Only add for Individual Users for now.
- However, the "loading" text still appears for all the Cards. It seems to be a mechanism from Flutter as all "loading" texts from the code have been removed.
- This is the temporary fix for now.

**Comment by NeilanshTriesToCode** [comment]
- Replaced loading texts with Loading Spinners using the ``CircularProgressIndicator`` element from flutter.
- Added style for color and wrapped it in a ``Center`` element (which is wrapped inside a ``SizedBox`` element) to place it in the center of the page. 
- So now a Loading Spinner appears when data is being read from firebase, both for individual and restaurant user dashboards/homepages.

**Comment by NeilanshTriesToCode** [comment]
Issue resolved.
