### ISSUE TITLE
Research similar apps.

### ISSUE THREAD

**Issue by minhhbt** [COSC-499-EquiFood-B/EquiFoodApp-B#5]

**Comment by anamicasunder** [comment]
A similar app is "too good to go"

**Comment by minhhbt** [comment]
Olio - also includes non-food items

**Comment by NeilanshTriesToCode** [comment]
FoodCloud - specifically for businesses (supermarkets, restaurants) dealing with leftovers. Local communities (shelters, NGOs) get informed about food that is put on the app by the business, which is later collected.

**Comment by minhhbt** [comment]
Discussed with team.
